#ifndef BDL_DEFAULTS_H
#define BDL_DEFAULTS_H

#define BDL_DEFAULT_BLOCKSIZE 512
#define BDL_MINIMUM_BLOCKSIZE 512
#define BDL_BLOCKSIZE_DIVISOR 256

// Default header pad 2kB
#define BDL_DEFAULT_HEADER_PAD 256*1024
#define BDL_MINIMUM_HEADER_PAD 1024
#define BDL_HEADER_PAD_DIVISOR 256

#define BDL_DEFAULT_PAD_CHAR 0xff

#endif
